### ISSUE TITLE
Need for silent screen output

### ISSUE THREAD

**Issue by jorishey1234** [EconForge/interpolation.py#18]
Installing with with pip install https://github.com/EconForge/interpolation.py works on Ubuntu but a call to LinearSpline or other functions returns extensive and unwanted screen output, for instance:

[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)
Setting
Setting
Setting
Setting
Setting
Setting
Setting
Setting
[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
[20 20]
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)
(20, 20)

Would it be possible to turn it off in next version ?
Thanks,
Joris

**Comment by sglyon** [comment]
Yes, we should definitely turn that off. 

Can you please provide some sample code that leads to output like that? Thanks

**Comment by albop** [comment]
I think the print statements come from multilinear.py, the set_values methods. These statements should just be removed. @jorishey1234 : would you do a PR ?

**Comment by jorishey1234** [comment]
This is an example code 

`import numpy as np
from interpolation.splines import LinearSpline

d=20

# 2D Random Field between -d/2,d/2
indexes=np.arange(-d/2,d/2,1)
A=np.random.randn(len(indexes),len(indexes))
S=LinearSpline(np.array([-d/2,-d/2]),np.array([d/2,d/2]),A.shape,A);

# Interpolation on random point clouds
n=100
x=np.vstack((np.random.rand(n)*d-d/2,np.random.rand(n)*d-d/2)).T
a=S(x)
`

which gives the output

`
Setting
[20 20]
(20, 20)
`

**Comment by albop** [comment]
closed by #19
