### ISSUE TITLE
Syntax Error in mlinterp.py upon import

### ISSUE THREAD

**Issue by MaximilianHoffmann** [EconForge/interpolation.py#25]
`in interpolation\multilinear\mlinterp.py", line 38
    def mlininterp(grid: Tuple, c: Array, u: Tuple)->float:
                       ^
SyntaxError: invalid syntax`

Is this a because I am running python3 ?

**Comment by albop** [comment]
Sounds doubtful. We now assume python>=3.6. What is your setup ?

**Comment by albop** [comment]
That looks a lot like python 3.5. Do you have the ability to update to Python 3.6 ?

**Comment by MaximilianHoffmann** [comment]
> certifi                   2018.8.24                py36_0    conda-forge
> llvmlite                  0.24.0                    <pip>
> numba                     0.39.0                    <pip>
> numpy                     1.15.1                    <pip>
> pip                       18.0                     py36_1    conda-forge
> python                    3.6.6                he025d50_0    conda-forge
> scipy                     1.1.0                     <pip>
> setuptools                40.2.0                   py36_0    conda-forge
> vc                        14                            0    conda-forge
> vs2015_runtime            14.0.25420                    0    conda-forge
> wheel                     0.31.1                   py36_1    conda-forge
> wincertstore              0.2                      py36_2    conda-forge

**Comment by MaximilianHoffmann** [comment]
I don't know, what cause the problem, but 

> backcall                  0.1.0                      py_0    conda-forge
> blas                      1.0                         mkl
> bleach                    2.1.4                      py_1    conda-forge
> ca-certificates           2018.8.24            ha4d7672_0    conda-forge
> certifi                   2018.8.24                py36_0    conda-forge
> cloudpickle               0.5.5                      py_0    conda-forge
> colorama                  0.3.9                      py_1    conda-forge
> cycler                    0.10.0                     py_1    conda-forge
> dask-core                 0.19.1                     py_0    conda-forge
> decorator                 4.3.0                      py_0    conda-forge
> defusedxml                0.5.0                    py36_0    conda-forge
> entrypoints               0.2.3                    py36_2    conda-forge
> freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
> html5lib                  1.0.1                      py_0    conda-forge
> icu                       58.2                     vc14_0  [vc14]  conda-forge
> imageio                   2.3.0                      py_1    conda-forge
> ipykernel                 4.9.0                    py36_0    conda-forge
> ipython                   6.5.0                    py36_0    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> jedi                      0.12.1                   py36_0    conda-forge
> jinja2                    2.10                       py_1    conda-forge
> jpeg                      9b                       vc14_2  [vc14]  conda-forge
> jsonschema                2.6.0                    py36_2    conda-forge
> jupyter_client            5.2.3                      py_1    conda-forge
> jupyter_core              4.4.0                      py_0    conda-forge
> kiwisolver                1.0.1            py36he980bc4_2    conda-forge
> libflang                  5.0.0             vc14_20180208  [vc14]  conda-forge
> libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
> libsodium                 1.0.16                   vc14_0  [vc14]  conda-forge
> libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
> llvm-meta                 5.0.0                         0    conda-forge
> llvmlite                  0.24.0                    <pip>
> m2w64-gcc-libgfortran     5.3.0                         6
> m2w64-gcc-libs            5.3.0                         7
> m2w64-gcc-libs-core       5.3.0                         7
> m2w64-gmp                 6.1.0                         2
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2
> markupsafe                1.0              py36hfa6e2cd_1    conda-forge
> matplotlib                2.2.2                    py36_1    conda-forge
> mistune                   0.8.3            py36hfa6e2cd_2    conda-forge
> mkl                       2017.0.3                      0
> msys2-conda-epoch         20160418                      1
> nb_conda                  2.2.1                    py36_0    conda-forge
> nb_conda_kernels          2.1.1                    py36_1    conda-forge
> nbconvert                 5.4.0                         0    conda-forge
> nbformat                  4.4.0                      py_1    conda-forge
> networkx                  2.1                        py_1    conda-forge
> notebook                  5.5.0                    py36_0    conda-forge
> numba                     0.39.0                    <pip>
> numpy                     1.15.1                    <pip>
> numpy                     1.13.1                   py36_0
> olefile                   0.45.1                     py_1    conda-forge
> openblas                  0.2.20                   vc14_8  [vc14]  conda-forge
> openmp                    5.0.0                    vc14_1  [vc14]  conda-forge
> openssl                   1.0.2p               hfa6e2cd_0    conda-forge
> pandas                    0.23.4           py36h830ac7b_0    conda-forge
> pandoc                    2.2.2                hde52d81_1    conda-forge
> pandocfilters             1.4.2                      py_1    conda-forge
> parso                     0.3.1                      py_0    conda-forge
> patsy                     0.5.0                      py_1    conda-forge
> pickleshare               0.7.4                    py36_0    conda-forge
> pillow                    5.2.0                    py36_0    conda-forge
> pip                       18.0                     py36_1    conda-forge
> prompt_toolkit            1.0.15                     py_1    conda-forge
> pygments                  2.2.0                      py_1    conda-forge
> pyparsing                 2.2.0                      py_1    conda-forge
> pyqt                      5.6.0            py36h764d66f_7    conda-forge
> python                    3.6.6                he025d50_0    conda-forge
> python-dateutil           2.7.3                      py_0    conda-forge
> pytz                      2018.5                     py_0    conda-forge
> pywavelets                1.0.0            py36h452e1ab_0    conda-forge
> pywinpty                  0.5.4                    py36_1    conda-forge
> pyzmq                     17.1.2           py36hf576995_0    conda-forge
> qt                        5.6.2                    vc14_1  [vc14]  conda-forge
> scikit-image              0.14.0           py36h6538335_1    conda-forge
> scipy                     0.19.1              np113py36_0
> scipy                     1.1.0                     <pip>
> seaborn                   0.9.0                      py_0    conda-forge
> send2trash                1.5.0                      py_0    conda-forge
> setuptools                40.2.0                   py36_0    conda-forge
> simplegeneric             0.8.1                      py_1    conda-forge
> sip                       4.18.1           py36h6538335_0    conda-forge
> six                       1.11.0                   py36_1    conda-forge
> statsmodels               0.9.0                    py36_0    conda-forge
> terminado                 0.8.1                    py36_1    conda-forge
> testpath                  0.3.1                    py36_1    conda-forge
> tifffile                  0.15.1                    <pip>
> tk                        8.6.8                    vc14_0  [vc14]  conda-forge
> toolz                     0.9.0                      py_0    conda-forge
> tornado                   5.1              py36hfa6e2cd_1    conda-forge
> traitlets                 4.3.2                    py36_0    conda-forge
> vc                        14                            0    conda-forge
> vs2015_runtime            14.0.25420                    0    conda-forge
> wcwidth                   0.1.7                      py_1    conda-forge
> webencodings              0.5.1                      py_1    conda-forge
> wheel                     0.31.1                   py36_1    conda-forge
> wincertstore              0.2                      py36_2    conda-forge
> winpty                    0.4.3                         4    conda-forge
> zeromq                    4.2.5                    vc14_2  [vc14]  conda-forge
> zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

now it works.

**Comment by albop** [comment]
Cool!
