### ISSUE TITLE
in readme example exchange ^ (bitwise xor) with **

### ISSUE THREAD

**Issue by MaximilianHoffmann** [EconForge/interpolation.py#27]
`S = np.random.random((10^6,3)`

**Comment by MaximilianHoffmann** [comment]
And maybe change comment about number of points to 50.

**Comment by gokceneraslan** [comment]
Thanks for writing this, I was also super confused.

**Comment by albop** [comment]
Thank you @MaximilianHoffmann  and @gokceneraslan , sorry for my slow response. I fixed the README file accordingly.
