### ISSUE TITLE
Returning a function for a non-grid domain (replacement for Scipy's `LinearNDInterpolation`)

### ISSUE THREAD

**Issue by cdagnino** [EconForge/interpolation.py#36]
With `LinearNDInterpolation` it is possible to get an interpolation function on an irregular grid.
For example

```
from scipy.interpolate import LinearNDInterpolator
interp_f = LinearNDInterpolator(points=[[1., 1.], [2.5, 2.], [2., 0.8]], 
                              values=[2., 10., 11.])
interp_f(2., 1.1)
#Gives: array(9.73076923)
```

Is there such functionality in `interpolation.py`, whether with one or multiple dimensions?

I saw that `interpolation.interp`handles non regular points, but the example only shows it returning points, not a function:

```
from interpolation import interp
x = np.linspace(0,1,100)**2 # non-uniform points
y = np.linspace(0,1,100)    # values
# interpolate at one point:
interp(x, y, 0.5)
```

**Comment by albop** [comment]
Irregular grid are now supported
