### ISSUE TITLE
cannot import name 'UCGrid', 'CGGrid', or 'nodes'

### ISSUE THREAD

**Issue by arnauq** [EconForge/interpolation.py#39]
Hi there,

following the example on the readme file, the line

`from interpolation.splines import UCGrid, CGrid, nodes`

results in a failed import. I've tried with the conda version and directly installing it from GitHub with the same result. Any ideas?

Thanks for your time.

**Comment by albop** [comment]
This is a bit surprising given that they are defined directly in `interpolation.splines.__init__.py`
It should work if you install the github version directly (conda and pypi are not updated yet). Have you tried to uninstall any previous version (pip uninstall and conda remove) ?

**Comment by arnauq** [comment]
Hi Pablo, thanks for the quick answer. I think there was a problem with different versions of packages conflicting with each other. I have now reinstalled the conda virtual environment with the github version if interpolation.py and it's working fine,

thanks!
