### ISSUE TITLE
No Module eval_cubic_cuda

### ISSUE THREAD

**Issue by avivajpeyi** [EconForge/interpolation.py#48]
Line 50 of interpolation.py/misc/speed_comparison_cuda.py:

`from interpolation.splines.eval_cubic_cuda import vec_eval_cubic_spline_3 as original`

There is no module named eval_cubic_cuda

**Comment by albop** [comment]
Indeed @avivajpeyi, cuda code disappeared. It should not be too hard to get it back. I'll leave this issue open. Note that CUDA support was experimental. It would make sense to bring back the file eval_cubic_cuda and put it in the `test` directory. If you want to run your own performance tests with a gpu, you can get the file `interpolation.splines.eval_cubic_cuda` from commit https://github.com/EconForge/interpolation.py/commit/28cb460d9b71b0ff77e865b2274396d7a1c411ee

**Comment by avivajpeyi** [comment]
ok! Thanks!
