### ISSUE TITLE
License

### ISSUE THREAD

**Issue by YuuuuXie** [EconForge/interpolation.py#54]
Hi,
I really appreciate your spline code, and used it in one project. Very soon we're going to release the project, just wonder if you can get a license (e.g. MIT license), such that we can claim the code of yours in our code.

Thanks!

**Comment by albop** [comment]
Thanks for your interest. BSD-2 is the license so it should be compatible most projects. I'll keep this issue open, until we add a propoer LICENSE file.

**Comment by albop** [comment]
LICENSE file was added. Closing now.
