### ISSUE TITLE
Replacement for scipy's RegularGridInterpolator

### ISSUE THREAD

**Issue by jvines** [EconForge/interpolation.py#55]
Hi,

I'm currently using Scipy's RegularGridInterpolator to interpolate ~20 3 dimensional grids and then pickle the resulting functions for later use. Would this be possible with this package? If so, would the resulting functions be faster than the ones from scipy??

Thank you!

**Comment by albop** [comment]
There is a LinearSpline object (which behaves like a function since it has a __call__ method). I have no idea whether it is pickable already. It probably is, but if it's not, it would be an easy feature to add. Can you try?
In terms of speed, that should be pretty independent from pickability.

**Comment by jvines** [comment]
Bu could I do an N dimensional interpolation with LinearSpline??

**Comment by albop** [comment]
Sure
