### ISSUE TITLE
One fix found for an error in fungen.py 

### ISSUE THREAD

**Issue by aouazad** [EconForge/interpolation.py#56]
I needed to replace
> from numba.types.containers import Tuple, UniTuple

by

> from numba.types import Tuple, UniTuple

in fungen.py. My setup is Python 3.6.9, and numba 0.49.

**Comment by albop** [comment]
Thank you @aouazad. This was fixed by pr #58 . I'll do a fix release (I'd like to setup some automatic process).

**Comment by albop** [comment]
Fixed in latest release 2.1.4
