### ISSUE TITLE
Conda and pip versions.

### ISSUE THREAD

**Issue by grburgess** [EconForge/interpolation.py#60]
Hi! This package is really great. I am curious if the version on conda and pip are the same. I’m having issues installing both as things seem to be missing. 

I would like to fix with a PR, but I’m not used to this poetry System. Is it possible to switch to the standard setup tools?

**Comment by albop** [comment]
What error do you get? I spent some time last week updating the build system and might have messed up something. 
As for the standard setup tools, it's not clear there is a standard anymore ;-) Except the pyproject.toml whose content is not actually standardized. I"ll open a separate issue to see how to regenerate another setup.py file, in sync with pyproject.toml.

**Comment by grburgess** [comment]
with pip, I got an issue with my package installing on travis-ci that the Jupyter checkpoints folder was missing. Not really sure what that means. When installing via conda on travis, eval_linear was not present in the distro.

**Comment by albop** [comment]
ok, thanks, what a mess. Let me fix that, I'm on it.

**Comment by grburgess** [comment]
no worries!

**Comment by albop** [comment]
Just out of curiosity, does it work with the pip version if you do `from interpolation.splines import eval_linear` ?

**Comment by grburgess** [comment]
it does, locally I have pip installed. but one of my packages builds on travis with conda.

**Comment by albop** [comment]
okay, so there are two separate issues:
-

**Comment by albop** [comment]
@grburgess : can you check again, please? PyPI and conda packages are freshly released, the latter based on the former so there should be no mismatch. PyPI packages are now based by github on tagged releases. I'll open two other issues for the `setup.py` and having `eval_linear` imported in the widest module scope (not sure it's very urgent).

**Comment by grburgess** [comment]
checking now. Thanks!

**Comment by grburgess** [comment]
I confirm that it is working now! Thanks a lot. Once I figure out the packaging system, I will have some features in a PR. Cheers.
