### ISSUE TITLE
Failing to import jitclass from numba

### ISSUE THREAD

**Issue by TheBobby** [EconForge/interpolation.py#80]
Just to let you know

When importing eval_linear from splines : 
`from interpolation.splines import eval_linear`
an ImportError is raised:

> ImportError: cannot import name 'jitclass' from 'numba' (/usr/local/lib/python3.7/site-packages/numba/__init__.py)

I learned from the numba github that jitclass has been moved to numba.experimental : 
https://github.com/numba/numba/issues/4638

Changing the corresponding line (line 3 in `__init__.py`) to 
`from numba.experimental import jitclass`
fixed it for me.

Thanks!

**Comment by albop** [comment]
Thank you, @TheBobby . Actually, jitclass is not used in the code anymore.
Bug was fixed a while ago in master. I"m updating the packages on pypi and conda-forge

**Comment by albop** [comment]
This is now fixed in master and released.
