### ISSUE TITLE
1D interpolation with eval_linear

### ISSUE THREAD

**Issue by grburgess** [EconForge/interpolation.py#89]
I'm trying to figure out how to use eval_linear for 1D interpolation. I know that I can use the interp function for this... but that is causing some pickle error when doing any kind of multiprocessing. 

What I have tried is this:

```python
grid = np.linspace(0., np.pi, 10) ,
value = np.sin(grid).reshape((1, 10))

eval_linear(grid, value, np.atleast_2d([0.5]))

```

But the output is not making sense. 

Am I missing something?

**Comment by albop** [comment]
In the example you give, grid is 1d so values should be représented by a 1d Vector. In your example it id a 2d Vector. Also, grid should be a tupe of 1d components.

**Comment by grburgess** [comment]
@albop here I will try a better example.

1) the comma after the grid definition packs the grid in a tuple

```python 

grid = np.linspace(0., np.pi, 10),

value = np.sin(grid).reshape((1,10))

xx = np.linspace(0.,np.pi,2)

eval_linear(grid, value, np.atleast_1d(xx))

```
output:
```bash
array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])
```

It seems it only evals at the grid point and not the new points.

**Comment by albop** [comment]
Second instruction still looks looks wrong to me:
- how Can the argument to np.sin be a tupe ? It shouldn't work.
- values should be a 1d array with 10 values not a 1 times 10 Matrix.
As for the last one since you interpolate on 10 1d points, you should pass
a 10 Times 1 Matrix.

**Comment by albop** [comment]
Here is a working version:
```python
grid = np.linspace(0., np.pi, 10),
value = np.sin(grid[0])                   # a 1d array
xx = np.linspace(0.,np.pi,2)          # a 1d array
eval_linear(grid, value, xx[:,None]) # xx[:,None] is a 2x1 array
```

**Comment by grburgess** [comment]
Thanks! Now I get the logic
