### ISSUE TITLE
`curses` requirement?

### ISSUE THREAD

**Issue by Mv77** [EconForge/interpolation.py#97]
@albop, after your recent patch for the derivatives issue, installing `interpolation` and importing `splines` results in the following error on Windows:
```
HARK\econforgeinterp.py:2: in <module>
    from interpolation.splines import eval_linear, eval_spline, CGrid
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\interpolation\splines\__init__.py:1: in <module>
    from curses import A_ALTCHARSET
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\curses\__init__.py:13: in <module>
    from _curses import *
E   ModuleNotFoundError: No module named '_curses'
```
It comes from this line, which was introduced by the patch
https://github.com/EconForge/interpolation.py/blob/578253472f715338c3e8b5d5032b145f2d11f781/interpolation/splines/__init__.py#L1

The issue is that [curses is not included in Windows's Python installation](https://docs.python.org/3/howto/curses.html). I don't see the import being used, could it be removed? or added to the requirements?

Sorry I did not bring this up in my checks, I ran them on a Linux machine.

**Comment by albop** [comment]
Ah we need to fix that. Maybe it was added by black. I'll Do that very
shortly

**Comment by Mv77** [comment]
Thanks!

Sorry to bother you again, but I also wanted to ask, why do you require grids to have a length greater than 2?
https://github.com/EconForge/interpolation.py/blob/578253472f715338c3e8b5d5032b145f2d11f781/interpolation/splines/__init__.py#L28
Would 2 points not suffice for it to work as a line?

**Comment by albop** [comment]
You're not bothering me at all. On the opposite!

Yes the check is useless. You need more than 2 points if you want higher
order splines but it shouldn't bé a critérium satisfied by thé grid object.
Plus we are not making thé check for regular grids. I'll put n>=2

**Comment by albop** [comment]
OK, I made both fixes and pushed the result. Not clear how I added the curse dependency. I suppose my editor went overzealous...

**Comment by albop** [comment]
This is now on pypi.

**Comment by Mv77** [comment]
Awesome!

Thank you @albop. Yeah, I've found VScode and black adding the strangest packages to my scripts lately. Weird and annoying.

But thanks for fixing it so quickly!
