### ISSUE TITLE
Python 3.10 support 

### ISSUE THREAD

**Issue by jan-janssen** [EconForge/interpolation.py#98]
I noticed the Conda-forge package enforces python `<3.10`, does this mean the package is incompatible to python 3.10? If that is not the case - I opened a pull request to include python 3.10 support for the Conda-forge package: 
https://github.com/conda-forge/interpolation-feedstock/pull/24

**Comment by jan-janssen** [comment]
It is not only the Conda-froge package but also the pip package https://github.com/EconForge/interpolation.py/blob/master/pyproject.toml#L17

**Comment by albop** [comment]
Hi @jan-janssen , I updated the requirements to 3.10 (and dropped 3.7). It is uploaded on pypi, and will be soon in conda
